### ISSUE TITLE
Segfault when calling NautyDense([], [], 0, false, false);

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/NautyTracesInterface#17]
Just to report that since some recent change in `NautyTracesInterface` we now get the following error in the Digraphs package:

~~~~
gap> DigraphsUseNauty();
#I  Using NautyTracesInterface by default for AutomorphismGroup
gap> CliqueNumber(NullDigraph(0));
Segmentation fault: 11
~~~~

I'm not sure if this is a bug in `Digraphs` or here, I reported it as an issue in both places for now. The Digraphs issue is:

https://github.com/gap-packages/Digraphs/issues/114

**Comment by james-d-mitchell** [comment]
This comes down to the following:

~~~~
NautyDense([], [], 0, false, false);
Segmentation fault: 11
~~~~

In other words, it looks like `NautyTracesInterface` does not handle empty graphs. I'm not sure if this is a bug or a feature, or why this didn't show up previously. This is easy to circumvent in Digraphs, but maybe you want to fix or document this anyway @sebasguts @markusbaumeister

**Comment by sebasguts** [comment]
This is almost certainly not a feature at all :). I will have a look at it asap.

**Comment by fingolfin** [comment]
Another segfault: `NautyDense( [1], [2], 3, false, false );`
