### ISSUE TITLE
NautyTracesInterface compatibility with GAP 4.9 was broken

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/NautyTracesInterface#33]
By commit https://github.com/gap-packages/NautyTracesInterface/commit/3dbd4fbe1fc0d699d0442ef670b3884f46bfba8e.  Just so we don't forget!

**Comment by james-d-mitchell** [comment]
The CI for NautyTracesInterface also failed (it seems like the CI correctly checked that the change in commit 3dbd4fb made Digraphs broken), I'm not sure why the change was committed anyway...
@fingolfin any chance that you could revert this change or otherwise fix it?

**Comment by fingolfin** [comment]
Sorry about this, that was bad (I naively thought this was a trivially obvious change with no possible bad result -- that was of course stupid, not sure what lead me to that idea. Anyway, I am working on a "proper" fix (by updating the find_gap m4 code for autoconf), which I will submit to all (?) affected repos ASAP

**Comment by fingolfin** [comment]
See PR #35
